web:
  build: ./lemp/
  environment:
    - HOSTNAMES=www.upstream-tracker.com
#    - http_proxy=http://buc-net-proxy.ubisoft.org:3128
#    - https_proxy=http://buc-net-proxy.ubisoft.org:3128
  ports:
    - "9001:80"
  links:
    - tracker:tracker.upstream-tracker.com
  volumes:
    - ./data/web/var/lib/mysql:/var/lib/mysql
    - ../website:/var/www

tracker:
  build: ./lemp/
  environment:
    - HOSTNAMES=tracker.upstream-tracker.com
#    - http_proxy=http://buc-net-proxy.ubisoft.org:3128
#    - https_proxy=http://buc-net-proxy.ubisoft.org:3128
  ports:
    - "9002:80"
  volumes:
    - ./data/tracker/var/lib/mysql:/var/lib/mysql
    - ../tracker:/var/www

selenium:
  build: ./selenium/
  ports:
    - "4444:4444"  
    - "5900:5900"
